In [6]:
import pandas as pd
df = pd.read_excel('CTG.xls', sheet_name='Raw Data', skiprows=0, skipfooter = 3)
#makes it so there are only the data columns
df = df.drop(['FileName', 'Date', 'SegFile'], axis=1)

import numpy as np
#replaces inf with nan
df = df.replace([np.inf, np.nan], np.nan)
#replaces anything that goes over the max value wiht nan
df = df.replace([np.finfo(np.float64).max], np.nan)
#replaces nan with mean
df = df.fillna(df.mean())

df

,b,e,LBE,LB,AC,FM,UC,ASTV,MSTV,ALTV,...,C,D,E,AD,DE,LD,FS,SUSP,CLASS,NSP
0,878.439793,1702.877234,133.303857,133.303857,2.722484,7.241298,3.659925,46.990122,1.332785,9.84666,...,0.024929,0.0381,0.033866,0.156162,0.118532,0.050329,0.032455,0.092662,4.509878,1.304327
1,240.000000,357.000000,120.000000,120.000000,0.000000,0.000000,0.000000,73.000000,0.500000,43.00000,...,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,9.000000,2.000000
2,5.000000,632.000000,132.000000,132.000000,4.000000,0.000000,4.000000,17.000000,2.100000,0.00000,...,0.000000,0.0000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000
3,177.000000,779.000000,133.000000,133.000000,2.000000,0.000000,5.000000,16.000000,2.100000,0.00000,...,0.000000,0.0000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000
4,411.000000,1192.000000,134.000000,134.000000,2.000000,0.000000,6.000000,16.000000,2.400000,0.00000,...,0.000000,0.0000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2122,2059.000000,2867.000000,140.000000,140.000000,0.000000,0.000000,6.000000,79.000000,0.200000,25.00000,...,0.000000,0.0000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000
2123,1576.000000,2867.000000,140.000000,140.000000,1.000000,0.000000,9.000000,78.000000,0.400000,22.00000,...,0.000000,0.0000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000
2124,1576.000000,2596.000000,140.000000,140.000000,1.000000,0.000000,7.000000,79.000000,0.400000,20.00000,...,0.000000,0.0000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000
2125,1576.000000,3049.000000,140.000000,140.000000,1.000000,0.000000,9.000000,78.000000,0.400000,27.00000,...,0.000000,0.0000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000
2126,2796.000000,3415.000000,142.000000,142.000000,1.000000,1.000000,5.000000,74.000000,0.400000,36.00000,...,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000

In [2]:
from sklearn.model_selection import train_test_split

X = df.iloc[1:2126, 3:-2].values
Y = df.iloc[1:2126, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=42, gamma='auto')
svm.fit(X_train, y_train)

ValueError: Unknown label type: 'continuous'